name: canvasnote
version: '1.0'
summary: Note-taking & drawing app for 2-in-1 devices
description: |
  CanvasNote is a note-taking and drawing application for 2-in-1 devices with stylus support.
  
  Features:
  - Drawing and handwriting with stylus support
  - Multiple pen types (pen, pencil, highlighter, eraser)
  - Palm rejection for natural writing
  - PDF export functionality
  - Organization with subjects and pages
  
title: CanvasNote
license: MIT
icon: snap/gui/icon.png
contact: https://github.com/rajeshdhanda/canvasnote/issues
issues: https://github.com/rajeshdhanda/canvasnote/issues
source-code: https://github.com/rajeshdhanda/canvasnote
website: https://github.com/rajeshdhanda/canvasnote
confinement: strict
grade: stable

base: core24

platforms:
  amd64:

apps: 
  canvasnote:
    command: bin/python3 $SNAP/main.py
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.12/site-packages
      GI_TYPELIB_PATH: $SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:/usr/lib/x86_64-linux-gnu/girepository-1.0
      # Force GTK scaling to 1x to prevent double-scaling of icons
      GDK_SCALE: "1"
      GDK_DPI_SCALE: "1"

parts:
  canvasnote:
    plugin: python
    source: .
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-evdev
      - libgtk-4-1
      - libadwaita-1-0
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
    organize:
      snap/gui: meta/gui
    override-build: |
      craftctl default
      cp -r $CRAFT_PART_SRC/* $CRAFT_PART_INSTALL/
