name: notes2in1
version: '1.3'
summary: Note-taking & drawing app for 2-in-1 devices
description: |
  Notes2in1 is a comprehensive native Linux note-taking and drawing application 
  optimized for 2-in-1/tablet devices with stylus support. Features include:
  
  - Multiple input methods: text, handwriting, and drawing
  - Smart palm rejection with automatic stylus detection
  - Pressure-sensitive pen, textured pencil, and highlighter tools
  - Advanced selection and editing with copy/paste support
  - Subject-based library with multi-page A4 notes
  - Canvas mode for infinite whiteboard
  - Professional templates: blank, ruled, grid, dot grid
  - Auto-save functionality
  - Export to PNG and PDF

base: core22
confinement: strict
grade: stable
compression: lzo

architectures:
  - build-on: amd64

apps:
  notes2in1:
    command: usr/bin/python3 $SNAP/main.py
    desktop: usr/share/applications/notes2in1.desktop
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - removable-media
      - gsettings
      - network
    environment:
      PYTHONPATH: $SNAP:$SNAP/usr/lib/python3/dist-packages
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/usr/lib/girepository-1.0
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      GTK_USE_PORTAL: 1

parts:
  notes2in1:
    plugin: dump
    source: .
    stage-packages:
      - python3
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - gir1.2-gtk-4.0
      - gir1.2-adw-1
      - libgtk-4-1
      - libadwaita-1-0
      - libcairo2
      - libgirepository-1.0-1
      - python3-pil
      - python3-evdev
      - python3-reportlab
    override-build: |
      craftctl default
      # Remove unnecessary files from source
      rm -rf $CRAFT_PART_INSTALL/.git* $CRAFT_PART_INSTALL/snap $CRAFT_PART_INSTALL/parts $CRAFT_PART_INSTALL/prime $CRAFT_PART_INSTALL/stage $CRAFT_PART_INSTALL/overlay
      rm -f $CRAFT_PART_INSTALL/CHANGELOG.md $CRAFT_PART_INSTALL/README.md $CRAFT_PART_INSTALL/snap_readme.md
      rm -f $CRAFT_PART_INSTALL/RUNNING_METHODS.txt $CRAFT_PART_INSTALL/SNAP_QUICKSTART.txt 
      rm -f $CRAFT_PART_INSTALL/requirements.txt $CRAFT_PART_INSTALL/run_dev.sh $CRAFT_PART_INSTALL/test_snap.sh
      # Create logs directory
      mkdir -p $CRAFT_PART_INSTALL/logs
    stage:
      - -**/man
      - -**/doc
      - -**/lintian

  desktop-file:
    plugin: dump
    source: snap/gui
    organize:
      notes2in1.desktop: usr/share/applications/notes2in1.desktop
      notes2in1.png: usr/share/pixmaps/notes2in1.png
